name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Archive APK into ZIP
      run: |
        mkdir -p output
        cp app/build/outputs/apk/debug/app-debug.apk output/
        zip -r output/app-debug.zip output/
        
    - name: Upload ZIP Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-zip
        path: output/app-debug.zip
